- src/Cli/PhpCommands.php
- tests/PhpCommandsTest.php
Skip checks for newer versions for PHP releases that are EOL.
> CORE-1193: Skip EOL versions of PHP.

- LICENSE
- composer.json
- composer.lock
- src/Cli/PhpCommands.php
- src/Cli/ProjectCommands.php
- src/Git/Remote.php
- src/Update/Filters/AddComposerDependencies.php
- src/Update/Filters/ApplyPlatformPatches.php
- src/Update/Filters/CopyPlatformAdditions.php
- src/Update/Filters/FilterManager.php
- src/Update/Filters/UpdateFilterInterface.php
- src/Update/Methods/MergeUpstreamBranch.php
- src/Update/Methods/SingleCommit.php
- src/Update/Methods/UpdateMethodInterface.php
- src/Update/Methods/UpdateMethodTrait.php
- src/Update/Methods/WpCliUpdate.php
- src/Util/ComposerJson.php
- src/Util/JsonFile.php
- src/Util/ReleaseNode.php
- src/Util/TmpDir.php
- updatinate.yml
- Provides a definition for updating Drupal 9 upstream branches on drops-8.
- Factors out code into reusable filters.
- Adds support for non-stable tags, controlled via the `allow-pre-release` property.
> Add Drupal 9 update configuration.

- templates/wordpress-composer/composer.json
Allow composer 2 in wordpress-composer.
> [CMS-64] Allow composer 2 in wordpress-composer.

- tests/ProjectCommandsTest.php
This pull request makes tests less fragile.
Adds sleep after closing PRs to ensure it doesn't conflict in the next steps of the test.
> Add sleep command after closing existing PRs.

- src/Cli/OrgCommands.php
- src/Cli/ProjectCommands.php
- update-tool
This pull request adds new project:update-info command and moves org:analyze to this tool.
- Adds a mapping for Pantheon support level badges
- Adds new project:update-info command
- Move org:analyze command from hubph (and related utilities) into new OrgCommands file.
> CMS-433: New project:update-info command and move org:analyze to this tool.

- src/Cli/OrgCommands.php
- src/Cli/ProjectCommands.php
- src/Util/SupportLevel.php
This pull request adds support_level field to org:analyze command.
New default field added to org:analyze command.
I tested this with a temporary small change using "users" API instead of "organizations" and running the command against my Github account and it's getting the right data for Support Level field.
> CMS-434: Update org:analyze command to add support_level.

- LICENSE
- composer.json
- composer.lock
- src/Cli/OrgCommands.php
- src/Cli/ProjectCommands.php
- src/Util/ProjectUpdate.php
- src/Util/ProjectUpdateTrait.php
- src/Util/SupportLevel.php
This pull request adds a new command that takes a csv as argument and goes through all of the projects and update project info for each line.
- Also accept badge label in the project:update-info command argument
- Adds org:update-projects-info command
- Refactor project:info-update into trait to make it reusable
- I ran this command like this `./update-tool org:update-projects-info projects.csv --update-codeowners --update-support-level-badge` against this csv file: https://gist.github.com/kporras07/5daa2c67ba6ca8f808120a8e6234861c and it created this PR: https://github.com/kporras07/wordpress-network/pull/23/files
> CMS-435: Add new org:update-projects-info command.

- src/Cli/ProjectCommands.php
This pull request fixes the branch to push at the end of the project:derivative:update command.
Switches to use main-branch as the branch to push at the end of the derivative update command.
> Use the right branch to push at the end of the command.

- CHANGELOG.md
- src/Cli/PhpCommands.php
Add body text to the PR for automated cos-php updates.
Add body text to the PR for automated cos-php updates.
I prematurely merged an automated PHP patch version update before the new patch version had been actually released.  This change adds a reminder message to future engineers to wait two days for the announcement to appear on the php.net website.
> [CMS-491] Add body text to the PR for automated cos-php updates

- src/Cli/UpdateTerminusDocsCommands.php
This pull request fixes build error in documentation repo.
_complete command was causing the docs build process to break. This PR removes that command from the commands.json file.
> [CMS-451] Exclude complete command that causes errors in docs build.

- src/Cli/UpdateTerminusDocsCommands.php
This pull request improves the terminus:update-docs command.
- Fixes search and replace logic for site_env.
- Avoids daily PR creation if same Terminus release.
> [CMS-451] Avoid creating lots of PRs and get the search and replace working correctly.

- src/Cli/UpdateTerminusDocsCommands.php
This pull request fixes a couple of issues from previous PR.
- Use right variable for PR title.
- Use right class for WorkingCopy.
> Use right class for WorkingCopy and right prTitle variable.

- src/Cli/UpdateTerminusDocsCommands.php
This pull request adds default pr-body to terminus:update-docs command. 
Adds default PR body text to update-docs command.
This prevents a script from the docs team to fail because of empty PRs bodies.
> [CMS-451] Add default pr-body value.

- src/Cli/OrgCommands.php
This pull request makes some adjustments to org:update-projects-info command.
New options added to this command:
- skip-on-empty-support-level
- error-log-file
- codeowners-only-owner
- If asked to update support level and an invalid support level was provided, skip the row at all using the new "skip-on-empty-support-level" option.
- Logs failing repo names to a log file specified in new "error-log-file" option.
- Allow updating CODEOWNERS conditionally to only update it if given owner guessed by using the new "codeowners-only-owner" option.
> CMS-584: Updates to org:update-projects-info command.

- src/Cli/OrgCommands.php
- src/Util/SupportLevel.php
This pull request adds new options to org:analyze command and fixes issues handling support_level field.
- Added --no-forks option
- Added --only-public option
- Fixes support_level field handling
With this command executed like shown below, we could get a list of all public repos and their corresponding support level:
```
./update-tool org:analyze pantheon-systems --fields=full_name,support_level --no-forks --only-public
```
Then, if we use tools like wc and grep we could get counts really easily:
1) With this command you can get the total public repos under the given org:
```
./update-tool org:analyze pantheon-systems …
```
> [CMS-600] Add new options and improve support level handling in org:analyze command.

- src/Cli/ProjectCommands.php
- update-tool.yml
Tested with this PR: https://github.com/pantheon-systems/drops-8/pull/405
Note: I'll be closing it soon so that regular updatinator reopens it with the right user.
> [CMS-571] Close old PRs for project:upstream:update based on upstream preamble.

- update-tool.yml
WordPress 6.0 was released earlier, and the [derivative check](https://app.circleci.com/pipelines/github/pantheon-systems/updatinator/54253/workflows/30a0e471-1a0d-4afb-bde9-9e3d4f6011a4/jobs/72687) is not detecting the new update.
Before/after this change was implemented locally:
> Update version-pattern number for new major WP release

- src/Cli/ProjectCommands.php
- src/Update/Methods/WpCliUpdate.php
The update is executed multiple times in the same command so the DB should actually be dropped even if this is running in CI.
> [BUGS-5122] Force db drop for this new command.

- src/Cli/PluginCommands.php
Adds a body to the PR that is generated for plugins.
The one plugin that runs in this section, wp-launch-check, bumps the WP core version.  When the major/minor versions that are available right now are 6.0 and 6.0.1, it was odd to see a PR bump the version to 6.0 and 5.9.4.
> Add body to PR for plugins

- src/Update/Methods/WpCliUpdate.php
Before using the class property values to determine the output, we need to check if they've been set.
> Check if the properties exist

- src/Cli/ProjectCommands.php
- src/Git/WorkingCopy.php
Fixes silent failure on git checkout during the upstream:push-tags caused but untracked files when switching between versions.
- Addresses [BUGS-6290](https://getpantheon.atlassian.net/browse/BUGS-6290)
- Addresses https://github.com/pantheon-systems/WordPress/issues/364
- Dry-run tested with @kporras07 in CircleCI
[BUGS-6290]: https://getpantheon.atlassian.net/browse/BUGS-6290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGS-6290] Clear untracked files between tag loops

- src/Cli/FrameworkCommands.php
This pull request adds a reminder to rebuild cos-runtime-php when composer gets updated.
Added description to cos-framework-clis PR when composer is being updated.
Tested in https://github.com/pantheon-systems/cos-framework-clis/pull/130 by running update-tool locally.
> [LOPS-1600] Use pr_body during PR creation.

- src/Cli/PhpCommands.php
Restores automation for pantheon-php in cos-runtime-php following the re-combination of repos in https://github.com/pantheon-systems/cos-runtime-php/pull/405
> [CMSP-541] Update path for cos-php to match nested pantheon-php directory

- src/Cli/PhpCommands.php
PHP 7.4.31 DNE, so update tool stopped looking when not found
We are not actually automating 7.4 on the master branch, but making the change as I would like to use this to test updates to updatinator.
> Handle missing php7.4 version

- src/Update/Filters/CopyMuPlugin.php
Excludes files that are added in https://github.com/pantheon-systems/pantheon-mu-plugin/pull/26 of the Pantheon mu-plugin.
https://github.com/pantheon-systems/pantheon-mu-plugin/pull/26 adds new files in `/bin` and `/tests` as well as adding a new `phpunit.xml.dist` file. This excludes them in the workflow that copies the mu-plugin from the repository to the WordPress upstream.
> [CMSP-633] exclude the files that are added in mu-plugin version 1.2.1

- .github/workflows/publish.yml
This pull request: updates the `publish.yml` workflow to apply the appropriate permissions to the GitHub bot to write changes to itself for GitHub Enterprise
> [CMSP-726] add the permissions to write the release to the repository

- src/Cli/FrameworkCommands.php
This pull request: 
* changes the `>` for comparing WP-CLI versions to `version_compare` 
| New feature?  | no| Has tests?    | yes/no
| Deprecations? | yes/no (2.10 is no longer < 2.9? 🧌)
`>` does not work when 2.10 is equivalent to 2.1 instead of the next value after 2.9.
`version_compare` is more robust and purpose-built for this use case.
> [CMSP-881] use version_compare

- src/Util/ReleaseNode.php
Removes the trailing space when checking release version numbers (in case there is nothing in the announcement post title after the version)
> remove trailing space

- composer.json
Allows a composer plugin so the `composer release` script can run properly.
> allow php-http/discovery

- .github/workflows/publish.yml
Fixes the publish step so the tag name can appropriately be exported and used in the release that is created.
> Fix publish step

- .github/workflows/publish.yml
adds a `tag` value so when we hand-off to this workflow from the test the `release-action` knows what tag to use (since it's not in the `ref`).
> define the tag in the release-action step

- CODEOWNERS
Update CODEOWNERS for new team names. Replaces #127
> [SITE-1547] Update CODEOWNERS for new team names

- src/Update/Filters/CopyMuPlugin.php
Moving phpcs.xml to a file codacy expects. Need to now ignore the correct file in update tool.
> Changing phpcs file name in mu plugin
