pantheon-systems/update-tool

- .circleci/config.yml
- LICENSE
- composer.lock
- scenarios/phpunit5/composer.lock
- src/Cli/ApiTrait.php
- src/Cli/CICommands.php
- src/Util/CIUtilsTrait.php
- updatinate
- updatinate.yml
Add a command to cancel CircleCI builds
> Cancel current build

- src/Cli/PhpCommands.php
- tests/fixtures/home/test-configuration.yml
- updatinate.yml
Update tool to match monorepo changes
> Submit pull requests for the php cookbook to infrastructure project

- src/Cli/PhpCommands.php
- src/Git/WorkingCopy.php
- updatinate.yml
Improve handling of forked repos
> Forked repos

- LICENSE
- composer.lock
- tests/PhpCommandsTest.php
- tests/WhoamiTest.php
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
Short overview of what changed.
> Temporary test - what's going on with Travis?

- README.md
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
Short overview of what changed.
> [skip ci] update docs reflecting onelogin to vault migration

- src/Cli/ProjectCommands.php
- src/Git/WorkingCopy.php
- src/Update/Methods/DiffPatch.php
- updatinate.yml
This will allow us to create update PRs prior to the Pressflow update being merged.
> Introduce DiffPatch update method, and use it to update Drops 7.

- src/Cli/ProjectCommands.php
Add main-branch option to derivative command and push to this branch after pushing all the tags.
> Add main-branch option to derivative and push to this branch after pushing all the tags.

- src/Cli/ProjectCommands.php
- updatinate.yml
This pull request adds wordpress-network to updatinate
| Deprecations? | yes/no 
Adds wordpress-network to updatinate
> Add wordpress-network to updatinate.

- LICENSE
- composer.json
- composer.lock
- src/Cli/OrgCommands.php
This pull request adds a command to auto merge old PRs.
Depends on https://github.com/g1a/hubph/pull/47 and then update hubph in this tool
> CMS-437: Auto merge old PRs.

- src/Cli/TerminusCommands.php
- src/Cli/UpdateTerminusDocsCommands.php
- update-tool
This pull request: adds new `terminus:update-docs` command to update commands and releases in documentation repo.
New command added.
> CMS-451: New terminus:update-docs command.

- src/Cli/UpdateTerminusDocsCommands.php
This pull request improves new terminus:update-docs.
| Bug fix?      | yes/no
| New feature?  | yes/no 
Excludes non semver releases from generated file.
> Exclude non semver releases.

- LICENSE
- composer.lock
- src/Cli/ProjectCommands.php
- src/Git/WorkingCopy.php
This pull request adds a comment before closing a PR indicating the PR that superseded it.
Depends on https://github.com/g1a/hubph/pull/48
> [CMS-98] Comment when closing a PR.

- src/Cli/FrameworkCommands.php
- update-tool
- update-tool.yml
| Has tests?    | Not yet added
> [CMS-464] Automate WP-CLI updates

- src/Cli/FrameworkCommands.php
Fix issue where multiple PRs cannot exist for cos-framework-clis
> Adjust preamble to handle multiple prs

- .circleci/config.yml
This pull request updates CircleCI image for Mysql service.
Change from circleci to cimg docker image.
> [CMS-572] Move away from deprecated circleci image.

- src/Cli/OrgCommands.php
- src/Util/SupportLevel.php
This pull request updates support level badges content and adds a new option to allow a different pr-body if support level is unsupported.
> [CMS-584] Update badge contents and add pr-body-unsupported option.

- src/Git/WorkingCopy.php
- src/Util/ProjectUpdate.php
This pull request makes CMS-584 to use forks.
Use forks instead of trying to push to the original repository.
This PR also fixes a couple of bugs with the fork process in update-tool.
> [CMS-584] Use forks for PR creation.

- src/Cli/FrameworkCommands.php
Modification of the WP-CLI version comparison so older versions do not supersede newer. This change will prevent incorrect PRs such as https://github.com/pantheon-systems/cos-framework-clis/pull/76. Also modified the `$version` variable name and added some comments to improve readability.
> Modify WP-CLI version comparison so older versions do not supersede newer

- src/Cli/FrameworkCommands.php
- update-tool.yml
| Bug fix?      | yes/no
| New feature?  | yes/no 
| Deprecations? | yes/no 
Short overview of what changed.
> [CMS-670] Update composer in cos-framework-clis.

- templates/composer-scaffold/pantheonize.sh
See example PR: https://github.com/pantheon-systems/composer-scaffold/pull/2 (created from local machine to avoid code that will skip it because no upstream changes)
> [CMS-754] More changes to README.md.

- src/Update/Methods/DiffPatch.php
.patch file needs a final line break.
> [BUGS-5092] Add line ending at the end of the patch.

- README.md
Short overview of what changed.
update anchor: actively-maintained-support
> update anchor: actively-maintained-support

- LICENSE
- README.md
- composer.json
- composer.lock
- src/CircleCI/CircleAPI.php
- src/Cli/OrgCommands.php
The experimental 'org:analyze' command now also collects environment variable data from CircleCI.
> Add CircleCI env vars to org:analyze

- src/Cli/UpdateTerminusDocsCommands.php
This pull request updates the path to match the actual location in the repo.
Docs repo was recently changed so the file now lives in a different location. The automation should be aware of that.
> Update path for install.md file as it was changed in the repo.

- .github/workflows/publish.yml
- .github/workflows/test.yml
Fixes the publish action by passing the tag name from the test action that triggers it.
> Fix dispatch
